- update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -24,6 +24,168 @@ commands:
             echo 'export PROJECT_ROOT_DIR="/home/circleci/project"' >> "$BASH_ENV"
             echo 'export TEMPLATE_ROOT_DIR="project-3-udacity"' >> "$BASH_ENV"
             echo 'export PROJECT_TAG="tuancnh-Udacity-final-project-3"' >> "$BASH_ENV"
+  revert-migrations:
+    description: Revert the last migration
+    parameters:
+      workflow_id:
+        type: string
+    steps:
+      - run:
+          name: Revert migrations
+          when: on_fail
+          command: |
+            # Your Memstash or kvdb.io GET URL code goes here
+            # Example: Memstash.io
+            SUCCESS=$(curl -H "token: e52b52de-ee26-41a5-86e8-e8dcc3d995a5" --request GET https://api.memstash.io/values/migration_<< parameters.workflow_id >>)
+            # Example: kvdb.io
+            SUCCESS=$(curl --insecure  https://kvdb.io/9GE4jRtKznmVKRfvdBABBe/migration_<< parameters.workflow_id >>)
+            # Logic for reverting the database state
+            if (( $SUCCESS == 1 ));
+            then
+              cd ~/project/backend
+              npm install
+              npm run migration:revert
+            fi
+  destroy_environment:
+    parameters:
+      stack_name:
+        type: string
+      bucket_name:
+        type: string
+        default: ""
+      when:
+        default: "on_fail"
+        type: enum
+        enum: [ "always", "on_success", "on_fail" ]
+      aws-access-key-id:
+        default: AWS_ACCESS_KEY_ID
+        description: >
+          AWS access key id for IAM role. Set this to the name of
+          the environment variable you will use to hold this
+          value, i.e. AWS_ACCESS_KEY.
+        type: env_var_name
+      aws-region:
+        default: AWS_DEFAULT_REGION
+        description: >
+          Env var of AWS region to operate in
+          (defaults to AWS_DEFAULT_REGION)
+        type: env_var_name
+      aws-secret-access-key:
+        default: AWS_SECRET_ACCESS_KEY
+        description: >
+          AWS secret key for IAM role. Set this to the name of
+          the environment variable you will use to hold this
+          value, i.e. AWS_SECRET_ACCESS_KEY.
+        type: env_var_name
+      profile-name:
+        default: default
+        description: Profile name to be configured.
+        type: string
+    steps:
+      - run:
+          name: "Install AWS CLI"
+          when: << parameters.when >>
+          command: |
+            if aws --version | grep "aws-cli/" > /dev/null
+            then
+              echo "AWS CLI is already installed, skipping installation."
+              exit 0
+            fi
+            
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+      - run:
+          name: "Configure AWS credential"
+          environment:
+            PARAM_AWS_CLI_ACCESS_KEY_ID: <<parameters.aws-access-key-id>>
+            PARAM_AWS_CLI_SECRET_ACCESS_KEY: <<parameters.aws-secret-access-key>>
+            PARAM_AWS_CLI_REGION: <<parameters.aws-region>>
+            PARAM_AWS_CLI_PROFILE_NAME: <<parameters.profile-name>>
+          when: << parameters.when >>
+          command: |
+            if aws --version | grep "aws-cli/" > /dev/null
+            then
+              echo "Due to AWS CLI is already installed, skipping configuration AWS credential."
+              exit 0
+            fi
+            
+            PARAM_AWS_CLI_ACCESS_KEY_ID=$(eval echo "\$$PARAM_AWS_CLI_ACCESS_KEY_ID")
+            
+            PARAM_AWS_CLI_SECRET_ACCESS_KEY=$(eval echo "\$$PARAM_AWS_CLI_SECRET_ACCESS_KEY")
+            
+            PARAM_AWS_CLI_REGION=$(eval echo "\$$PARAM_AWS_CLI_REGION")
+            
+            if [ -z "$PARAM_AWS_CLI_ACCESS_KEY_ID" ] || [ -z "${PARAM_AWS_CLI_SECRET_ACCESS_KEY}" ]
+            then
+              echo "Cannot configure profile. AWS access key id and AWS secret access key must be provided."
+              exit 1
+            fi
+            
+            aws configure set \
+              aws_access_key_id "$PARAM_AWS_CLI_ACCESS_KEY_ID" \
+              --profile "$PARAM_AWS_CLI_PROFILE_NAME"
+            
+            aws configure set \
+              aws_secret_access_key "$PARAM_AWS_CLI_SECRET_ACCESS_KEY" \
+              --profile "$PARAM_AWS_CLI_PROFILE_NAME"
+            
+            aws configure set \
+              region "$PARAM_AWS_CLI_REGION" \
+              --profile "$PARAM_AWS_CLI_PROFILE_NAME"
+      - run:
+          name: "Empty << parameters.bucket_name >> bucket"
+          when: << parameters.when >>
+          shell: /bin/bash
+          command: |
+            bucket_name="<< parameters.bucket_name >>"
+            
+            if [[ -z $bucket_name ]]
+            then
+              echo "Skip the empty bucket action due to the empty bucket name"
+              exit 0
+            fi
+            
+            bucket_uri="s3://$bucket_name"
+            bucket_info=$(aws s3 ls $bucket_uri 2>&1)
+            
+            if echo $bucket_info | grep 'NoSuchBucket' > /dev/null
+            then
+              echo "Bucket doesn't exist, skip the empty bucket action"
+              exit 0
+            fi
+            
+            # Empty before delete the bucket
+            aws s3 rm $bucket_uri --recursive
+      - run:
+          name: "Delete << parameters.stack_name >> stack"
+          when: << parameters.when >>
+          shell: /bin/bash
+          command: |
+            # Get stack id for the delete_stack waiter
+            stack_info=$(aws cloudformation describe-stacks --stack-name << parameters.stack_name >> --query "Stacks[*] | [0].StackId" 2>&1)
+            if echo $stack_info | grep 'does not exist' > /dev/null
+            then
+              echo "Stack does not exist."
+              echo $stack_info
+              exit 0
+            fi
+            if echo $stack_info | grep 'ValidationError' > /dev/null
+            then
+              echo $stack_info
+              exit 1
+            else
+              aws cloudformation delete-stack --stack-name << parameters.stack_name >>
+              echo $stack_info
+              aws cloudformation wait stack-delete-complete --stack-name $stack_info
+              if [ "<< parameters.when >>" = "on_fail" ]
+              then
+                echo "Roll back completed. Green environment destroyed."
+                exit 0
+              fi
+              echo "Stack << parameters.stack_name >> cleaned up"
+              exit 0
+            fi
 jobs:
   build-frontend:
     docker:
