- update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -454,12 +454,15 @@ jobs:
           command: |
             URL="http://bucket-91019.s3-website-us-east-1.amazonaws.com/#/employees"            
             echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
+            test_result=$(curl -s "$URL")
+            if echo $test_result | grep "Welcome" > /dev/null
             then
-            	# Change this to 0 after the job fails
-              return 0
+              echo "Frontend test passed"
+              echo $test_result
+              exit 0
             else
-              return 1
+              echo $test_result
+              exit 1
             fi
       - run:
           name: "Backend smoke test"
@@ -467,12 +470,20 @@ jobs:
             export BACKEND_IP=$(aws ec2 describe-instances --query Reservations[*].Instances[*].PublicIpAddress --filters Name=tag:project,Values=project-3-backend --output text)
             export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
-            echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok"
+            curl --version
+            # When the backend server is not ready, let retry upto 30mins
+            test_result=$(eval curl \
+              --verbose --fail \
+              --retry 360 --retry-max-time 1800 --retry-all-errors \
+              --url "$API_URL/api/status")
+            if echo $test_result | grep "ok" > /dev/null
             then
-              return 0
+              echo "Backend test passed"
+              echo $test_result
+              exit 0
             else
-              return 1
+              echo $test_result
+              exit 1
             fi
 
   promote-to-production:
